version: "{build}"

os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

platform: x64
environment:
  matrix:
    - TARGET_CPU: x64
    - TARGET_CPU: x86

install:
  - ps: Install-Product node 8
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python27;%PATH%
  - cmd: node scripts/bootstrap.js --target-cpu=%TARGET_CPU%
  - cmd: node scripts/build.js out/Release
  - cmd: node scripts/create_dist.js

artifacts:
  - path: 'out\Release\*.zip'

deploy:
  - provider: GitHub
    release: GN $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '(placeholder)'
    auth_token:
      secure: A6p8IoStnodPh/lGnc41E+ACsYdyfOV3Z7K6H3w0Xz2SsLpL06AKb6PTNmMtWp1F
    artifact: /.*\.zip/
    draft: true
    force_update: true
    prerelease: false
    on:
      appveyor_repo_tag: true

# disable build and test pahses
build: off
test: off
